name: 🐛 Reportar Bug
description: Encontrou um problema? Ajude-nos a corrigi-lo!
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Por favor, preencha as informações abaixo para nos ajudar a entender e corrigir o problema.

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Descreva claramente o que está acontecendo de errado
      placeholder: Ex: Ao clicar no botão "Próxima Aula", a página fica em branco
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para Reproduzir
      description: Como podemos reproduzir o problema?
      placeholder: |
        1. Acesse a página '...'
        2. Clique em '...'
        3. Role até '...'
        4. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que deveria acontecer?
      placeholder: Ex: A próxima aula deveria carregar normalmente
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que está acontecendo na realidade?
      placeholder: Ex: A página fica em branco e aparece um erro no console
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Gravidade
      description: Quão grave é este bug?
      options:
        - 🔴 Crítico (impede uso da plataforma)
        - 🟠 Alto (funcionalidade importante quebrada)
        - 🟡 Médio (funcionalidade secundária afetada)
        - 🟢 Baixo (problema cosmético ou menor)
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Navegador
      description: Qual navegador você está usando?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Outro
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Dispositivo
      description: Onde você encontrou o bug?
      options:
        - Desktop (Windows)
        - Desktop (Mac)
        - Desktop (Linux)
        - Mobile (Android)
        - Mobile (iOS)
        - Tablet
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots ou Vídeos
      description: Se possível, adicione capturas de tela ou vídeos do problema
      placeholder: Cole aqui ou arraste imagens/vídeos

  - type: textarea
    id: console
    attributes:
      label: Erros do Console
      description: Abra o console do navegador (F12) e cole quaisquer erros que apareçam
      placeholder: |
        Uncaught TypeError: Cannot read property 'id' of undefined
        at LessonPage.tsx:42
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Qualquer outra informação relevante sobre o problema
      placeholder: Ex: O bug só acontece quando estou logado, ou apenas em páginas específicas

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Por favor, confirme que você
      options:
        - label: Pesquisei issues existentes e não encontrei este bug reportado
          required: true
        - label: Testei em um navegador diferente (se possível)
          required: false
        - label: Limpei o cache do navegador antes de testar
          required: false
